
  oracle_user: oracle 
  oracle_base: /u01/app/oracle

  # set rman_cronfile: "" for using the user cron
  rman_cronfile: oracle_rman_ansible
  rman_cron_logdir: /var/log/oracle/rman/log

  rman_script_dir: "{{oracle_admin_db}}/rman/"
  rman_log_dir: "{{oracle_admin_db}}/rman/log"

  rmanautofs: false

  rman_cron_mkjob: False

  oracle_home_db: "{% if item.0 is defined %}{% if item.0.oracle_home is defined %}{{ item.0.oracle_home}}{% else %}{{ oracle_base }}/{{ item.0.oracle_version_db }}/{{ item.0.home }}{% endif %}{% else %}{% if item.oracle_home is defined %}{{ item.oracle_home }}{% else %}{{ oracle_base }}/{{ item.oracle_version_db }}/{{ item.home }}{% endif %}{% endif %}"
  oracle_admin_db: "{% if item.0 is defined %}{{oracle_base}}/admin/{{item.0.oracle_db_name}}{% endif %}"

  rman_retention_policy_default: "RECOVERY WINDOW OF 14 DAYS"
  rman_channel_disk_default: "'/u10/rmanbackup/%d/%d_%T_%U'"
  rman_controlfile_autobackup_disk_default: "'/u10/rmanbackup/%d/%d_%F'"
  rman_device_type_disk_default: 'PARALLELISM 1 BACKUP TYPE TO COMPRESSED BACKUPSET'

  rman_retention_policy: "{% if item.0.rman_retention_policy is defined %}{{item.0.rman_retention_policy}}{% else %}{{rman_retention_policy_default}}{% endif %}"
  rman_channel_disk: "{% if item.0.rman_channel_disk is defined %}{{item.0.rman_channel_disk}}{% else %}{{rman_channel_disk_default}}{% endif %}"
  rman_controlfile_autobackup_disk: "{% if item.0.rman_controlfile_autobackup_disk is defined %}{{item.0.rman_controlfile_autobackup_disk}}{% else %}{{rman_controlfile_autobackup_disk_default}}{% endif %}"

  rman_service_param: "{% if item.1.service is defined %}--service {{item.1.service}}{% else %}{% endif %}"

  check_mk_mkjob: "{% if rman_cron_mkjob %}/usr/bin/mk-job rman_{{item.0.oracle_db_name}}_{{item.1.name}} {% endif %}"
