---
# todo:
# - Patchinstallation ermitteln
#   Liste der installierten Patches wird benoetigt, um Doppelinstallationen zu vermeiden.
#
# Restrictions:
# - Standby Databases
#   The role ignores the state of a database. That results in problems, when datapatch is started
# - old/new state of database is ignored in Single-Instace
#   The database is stopped before opatch apply and started before datapatch. It won't be stopped
#   after datapach if the instance was not running before!

  # environment is needed for OL/SLES, due to different directories for executables...
  # grep LOC= in /u01/app/oraInventory/ContentsXML/inventory.xml and search for LOC=
  - name: Get ORACLE_HOMEs from oraInventory
    shell: grep "LOC=" $(cat /etc/oraInst.loc | grep inventory_loc | cut -d"=" -f2)/ContentsXML/inventory.xml | sed 's#.*LOC=##g' | cut -d" " -f1 | /usr//bin/sed 's#"##g'
    environment:
      - PATH: /bin:/usr/bin
    register: inventory_oh_list
    tags:
      - gethomes
      - check_applied_patches
      - datapatchdbs
      - opatchapply
      - opatchprereq
      - stopalldbs

  # we only need the homes with are usable as oracle_user
  - name: Check owner of OPatch for inventory_oh_list
    ignore_errors: True
    file: path={{item}}/OPatch/opatch owner="{{ oracle_user }}" state=file
    with_items:
      - "{{inventory_oh_list.stdout_lines}}"
    register: usable_inventory_oh_list
    tags:
      - check_applied_patches
      - datapatchdbs
      - opatchapply
      - opatchprereq
      - stopalldbs

  - name: Set facts for ORACLE_HOMEs
    no_log: true
    set_fact:
      host_oracle_home: "{{host_oracle_home|default([]) + [{ 'oracle_home': item.item}]}}"
    with_items:
       - "{{usable_inventory_oh_list['results']}}"
    when: item.changed == false
    tags:
      - check_applied_patches
      - datapatchdbs
      - opatchapply
      - opatchprereq
      - stopalldbs

  - name: Set facts for patch and ORACLE_HOME in a list
    no_log: true
    set_fact: 
      patch_oh_list: "{{patch_oh_list|default([]) + [{'patchid': item.0.patchid, 'apply': item.1.apply|default(true), 'path': item.1.path, 'subpath': item.0.subpath|default(''), 'version': item.0.version, 'opatchauto': item.0.opatchauto }] }}"
    with_subelements:
      - "{{oracle_patch_list}}"
      - ORACLE_HOME
    when: item.0 is defined and item.1 is defined
    tags:
      - check_applied_patches
      - opatchautoapply
      - opatchapply
      - opatchprereq
      - stopalldbs

  - name: Mount nfs share with installation media
    mount: src="{{ nfs_server_sw }}:{{ nfs_server_sw_path }}" name={{ oracle_stage_remote }} fstype=nfs state=mounted
    tags:
      - nfsmount
      - updateopatch
      - opatchapply
      - opatchprereq
    when: install_from_nfs|bool

  - name: Create stage directory
    file: dest={{ oracle_psu_stage }}/{{ item.version }} mode=775 owner={{ oracle_user }} group={{ oracle_group }} state=directory
    with_items:
       - "{{oracle_patch_list}}"
    tags:
      - directoriespsu
    when: oracle_psu_apply_db

  - name: Extract OPatch to stage-area
    unarchive: src={{ oracle_stage }}/{{ item.1.filename }}  dest={{ oracle_psu_stage }}/{{ item.1.version }} copy=no
    become: yes
    become_user: "{{ oracle_user }}"
    with_nested:
      - "{{oracle_patch_list}}"
      - "{{oracle_opatch_patch}}"
    when: oracle_psu_apply_db and item.0.version == item.1.version and oracle_sw_unpack|bool
    tags:
      - oragridpatchunpack

#  - name: Extract RDBMS psu files to stage-area
#    unarchive: src={{ oracle_stage }}/{{ item.0.filename }}  dest={{ oracle_psu_stage }}/{{ oracle_install_version_gi }} copy=no
#    become: yes
#    become_user: "{{ oracle_user }}"
#    with_together:
#       - "{{oracle_sw_image_gi_psu}}"
#       - "{{gi_applied_patches.results}}"
#    when: oracle_psu_apply_db and oracle_sw_unpack|bool and "{{ item.0.version }}" == "{{ oracle_install_version_gi }}" and not {{ item.1.stdout }} != 0
#    tags:
#      - oragridpsuunpack

#  - name: set facts for unique ORACLE_HOME paths
#    set_fact:
#      db_oracle_home_list: "{{oracle_databases.oracle_home|unique }}"
#    tags:
#      - setfact


  # We have to remove the old OPatch to reduce the number of copy loops at later time.
  # Remember that many Database with same ORACLE_HOME may exists
  - name: Remove existing OPatch
    no_log: true
    file: path={{oracle_home_db}}/OPatch state=absent
    become: yes
    become_user: "{{ oracle_user }}"
    with_together:
      - "{{oracle_databases}}"
      - ""
    when: oracle_psu_apply_db
    tags:
      - updateopatch

  # use test -d to copy the OPatch only one time for many databases in oracle_databases!
  - name: Distribute latest opatch
    shell: "test -d {{oracle_home_db}}/OPatch || unzip -d {{oracle_home_db}} /sw/oracle/linux64/12.1.0.2/patch/p6880880_122010_Linux-x86-64.zip"
    with_together:
      - "{{oracle_databases}}"
      - ""
    become: yes
    become_user: "{{ oracle_user }}"
    when: oracle_psu_apply_db
    tags:
      - updateopatch

  # - name: Configure ocm.rsp (1)
  #   template: src=ocmrsp.expect.j2  dest={{ oracle_psu_stage }}/{{ oracle_install_version_gi }}/ocmrsp.expect mode=0777 force=yes
  #   when: oracle_psu_apply_db #and not {{ item.1.stdout }} != 0
  #   become: yes
  #   become_user: "{{ oracle_user }}"
  #   tags:
  #     - ocmconfig
  #
  # - name: Configure ocm.rsp (2)
  #   shell: "{{ oracle_psu_stage }}/{{ oracle_install_version_gi }}/ocmrsp.expect"
  #   when: oracle_psu_apply_db #and not {{ item.1.stdout }} != 0
  #   become: yes
  #   become_user: "{{ oracle_user }}"
  #   tags:
  #     - ocmconfig

  - name: Check which RDBMS patches are applied
    shell: "{{ item.oracle_home }}/OPatch/opatch lspatches -oh {{ item.oracle_home }}"
    become: yes
    become_user: "{{ oracle_user }}"
    with_items:
       - "{{host_oracle_home}}"
    when: oracle_psu_apply_db
    register: db_applied_patches
    tags:
      - check_applied_patches

  - debug: msg={{item.stdout_lines}}
    with_items: "{{db_applied_patches.results}}"
    tags:
      - check_applied_patches

  #
  - name: Copy helper script to stage
    copy: src={{ item }} dest={{ oracle_rsp_stage}} mode=755 
    with_items:
      - "datapatch_dbs_in_home.sh"
      - "stop_dbs_in_home.sh"
    tags:
      - copyrsp
      - datapatchdbs
      - stopalldbs

  - name: Stop Databases in Homes
    shell: "{{oracle_rsp_stage}}/stop_dbs_in_home.sh {{item.oracle_home}}"
    environment:
      - PATH: /bin:/usr/bin
    with_items:
       - "{{host_oracle_home}}"
    become: yes
    become_user: "{{ oracle_user }}"
    when: oracle_psu_apply_db and oracle_install_option_gi is not defined
    tags:
      - stopalldbs
      - opatchapply

  - name: Check requirements for Patches with OPatch (CheckConflictAgainstOHWithDetail )
    shell: "{{item.path}}/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -silent -oh {{item.path}} -ph {{patchpath}}"
    with_items:
       - "{{patch_oh_list}}"
    become: yes
    become_user: "{{ oracle_user }}"
    when: oracle_psu_apply_db and "12." in "{{ item.version }}" and not {{ item.opatchauto }} and {{ item.apply }}
    register: opatchprereq2
    changed_when: "'failed' in opatchprereq2.stdout"
    tags:
      - opatchprereq
      - opatchapply

  - debug: msg={{item.stdout_lines}}
    with_items:
       - "{{opatchprereq2.results[0]}}"
    when: item.changed
    tags:
      - opatchprereq
      - opatchapply

  - name: Check requirements for Patches with OPatch (CheckActiveFilesAndExecutables)
    shell: "{{item.path}}/OPatch/opatch prereq CheckActiveFilesAndExecutables -silent -oh {{item.path}} -ph {{patchpath}}"
    with_items:
       - "{{patch_oh_list}}"
    become: yes
    become_user: "{{ oracle_user }}"
    when: oracle_psu_apply_db and "12." in "{{ item.version }}" and not {{ item.opatchauto }} and {{ item.apply }} and oracle_install_option_gi is not defined
    register: opatchprereq1
    changed_when: "'failed' in opatchprereq1.stdout"
    tags:
      - opatchprereq
      - opatchapply

  - debug: msg={{item.stdout_lines}}
    with_items:
       - "{{opatchprereq1.results[0]}}"
    when: item.changed
    tags:
      - opatchprereq
      - opatchapply


  - name: Stop execution when CheckActiveFilesAndExecutables reports problems (non GI)
    fail: msg="Please review the debug output for reasons!"
    with_items:
       - "{{opatchprereq1.results[0]}}"
    when: item.changed and oracle_install_option_gi is not defined
    tags:
      - opatchprereq
      - opatchapply

  - name: Apply Patches with OPatch opatchauto
    shell: "{{item.path}}/OPatch/opatchauto apply -silent -oh {{item.path}}  {{patchpath}}"
    with_items:
       - "{{patch_oh_list}}"
    become: yes
    become_user: "{{ oracle_user }}"
    when: oracle_psu_apply_db and {{ item.opatchauto | default(false) }} and {{ item.apply | default(false)}}
    register: opatchapplyresult
    tags:
      - opatchautoapply

  - name: Apply Patches with OPatch apply
    shell: "{{item.path}}/OPatch/opatch apply -silent -oh {{item.path}}  {{patchpath}}"
    with_items:
       - "{{patch_oh_list}}"
    become: yes
    become_user: "{{ oracle_user }}"
    when: oracle_psu_apply_db and "12." in "{{ item.version }}" and not {{ item.opatchauto }} and {{ item.apply }}
    failed_when: "'failed' in opatchapplyresult.stdout"
    changed_when: not "'These patch(es) will be skipped' in opatchapplyresult.stdout"
    register: opatchapplyresult
    tags:
      - opatchapply

  - debug: msg={{item.stdout_lines}}
    with_items:
       - "{{opatchapplyresult.results[0]}}"
    when: item.changed
    tags:
      - opatchautoapply
      - opatchapply

  - name: Execute datapatch in every Home
    shell: "{{oracle_rsp_stage}}/datapatch_dbs_in_home.sh {{item.oracle_home}}"
    environment:
      - PATH: /bin:/usr/bin
    with_items:
       - "{{host_oracle_home}}"
    become: yes
    become_user: "{{ oracle_user }}"
    register: datapatchresult
    when: oracle_psu_apply_db and oracle_install_option_gi is not defined
    tags:
      - stopalldbs
      - opatchapply
      - datapatchdbs


  - debug: var={{item.stdout_lines}}
    with_items:
       - "{{datapatchresult.results}}"
    tags:
      - stopalldbs
      - opatchapply
      - datapatchdbs

#  - name: Check opatch lsinventory
#    shell: "{{ item.oracle_home }}/OPatch/opatch lsinventory"
#    with_items:
#       - "{{oracle_databases}}"
#    become: yes
#    become_user: "{{ oracle_user }}"
#    register: opatchls
#    when: oracle_psu_apply_db
#    tags:
#      - opatchls
#      - opatchapply
#      - opatchautoapply

#  - debug: var=item.stdout_lines
#    with_items: "{{opatchls.results}}"
#    when: oracle_psu_apply_db
#    tags:
#      - opatchapply
#      - opatchautoapply
#      - opatchls

