---

  - name: Check for valid  configuration of oracle_databases
    no_log: true
    assert:
      that:
        - item.1 is defined
    with_subelements:
       - "{{oracle_databases}}"
       - rman_jobs
    tags:
      - assert

  - name: Default Destinations for RMAN
    no_log: true
    assert:
      that:
        - rman_controlfile_autobackup_disk_default
        - rman_channel_disk_default
    tags:
      - assert

  # autofs is configured in a special way to mount the shares with needed parameters
  - name: configure autofs for RMAN
    lineinfile: dest=/etc/auto.master regexp="^{{rmanautofsmount}} " line="{{rmanautofsmount}} /etc/auto.net --timeout=60 rw,hard,rsize=32768,wsize=32768,proto=tcp,nfsvers=3"
    when: "rmanautofs"
    tags: autofs

  - name: Create Mountpoint
    file: dest={{rmanautofsmount}} state=directory
    when: "rmanautofs"
    tags: autofs

  - name: Restart autofs
    service: name=autofs enabled=yes state=restarted
    when: "rmanautofs"
    tags: autofs

  - name: Create bin-Directory for rman_backup
    file: path={{oracle_base}}/bin state=directory mode=0755
    tags:
      - rmancopy

  - name: Create log-Directory for cron output
    file: path={{rman_cron_logdir}} state=directory mode=0755 owner={{oracle_user}}
    tags:
      - rmancron
      - rmancopy

  # dummy with_together for item.0.db_name in default/main.yml 
  - name: Create Directory for rman-scripts
    file: path={{rman_script_dir}} state=directory mode=0755 owner={{oracle_user}}
    with_together:
       - "{{oracle_databases}}"
       - ""
    tags:
      - rmancopy

  # dummy with_together for item.0.db_name in default/main.yml
  - name: Create Directory for rman-logfiles
    file: path={{rman_log_dir}} state=directory mode=0755 owner={{oracle_user}}
    with_together:
       - "{{oracle_databases}}"
       - ""
    tags:
      - rmancopy

  - name: copy rman_backup.sh
    copy: dest={{oracle_base}}/bin src=rman_backup.sh backup=yes mode=755
    tags:
      - rmancopy

  # rman_script_dir: {{oracle_admin_db}}/rman/
  - name: copy RMAN scipts
    template: dest={{rman_script_dir}}/{{item.1.name}}.rman src={{item.1.name}}.rman.j2 backup=yes mode=644 owner={{oracle_user}}
    with_subelements:
       - "{{oracle_databases}}"
       - rman_jobs
    tags:
      - rmancopy

  # the following task is usefull for configuration of rman-parameters during setup of RMAN
  # It's also possible to execute the 1st Level0-Backup after setup, but be aware to configure the RMAN before starting a backup
  # The execution isn't done in async mode!
  # The task is only execute once on master_node when GI is installed!
  - name: Execute RMAN-Script at playbook
    shell: "{{oracle_base}}/bin/rman_backup.sh -a {{item.1.name}} -s {{item.0.oracle_db_name}} -r {{rman_script_dir}} -l {{rman_log_dir}} | tee -a {{rman_cron_logdir}}/rman_{{item.1.name}}.log"
    environment:
      - PATH: /bin:/usr/bin
    become: yes
    become_user: "{{ oracle_user }}"
    register: rmanexecimmediate
    with_subelements:
       - "{{oracle_databases}}"
       - rman_jobs
    when: master_node and item.1.immediate | default(false) == true
    tags:
      - rmanexecute

  - debug: msg={{item.results[0].stdout_lines}}
    with_items:
      - "{{rmanexecimmediate}}"
    when: rmanexecimmediate is defined and item.results[0].stdout_lines is defined
    tags:
      - rmanexecute

  - name: Create crontab entries for RMAN Backup
    cron: 
      name: rman_backup_{{item.0.oracle_db_name}}_{{item.1.name}}
      cron_file: "{{rman_cronfile}}"
      user: "{{oracle_user}}"
      disabled: "{{item.1.disabled}}"
      day: "{{item.1.day}}"
      weekday: "{{item.1.weekday}}"
      hour: "{{item.1.hour}}"
      minute: "{{item.1.minute}}"
      job: "{{ check_mk_mkjob }}{{oracle_base}}/bin/rman_backup.sh -a {{item.1.name}} -s {{item.0.oracle_db_name}} -r {{rman_script_dir}} -l {{rman_log_dir}} {{rman_service_param}} >> {{rman_cron_logdir}}/rman_{{item.0.oracle_db_name}}_{{item.1.name}}.log 2>&1"
    with_subelements:
       - "{{oracle_databases}}"
       - rman_jobs
    when: 
      - item.1 is defined 
      - item.1.disabled is defined
      - item.1.day is defined
      - item.1.weekday is defined
      - item.1.hour is defined
      - item.1.minute is defined
      - item.1.name is defined
    tags:
      - rmancron

  - name: Create directory for mk-job
    file: dest=/var/lib/check_mk_agent/job/{{oracle_user}} state=directory owner={{oracle_user}}
    when: "rman_cron_mkjob"
    tags: rmancron

