---

  master_node: true
  role_separation: false
  hostgroup: default
  configure_cluster: false
  oracle_psu_apply_db: true

  oracle_user: oracle                        # User that will own the Oracle Installations.
  oracle_user_home: "/home/{{ oracle_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  oracle_group: oinstall                          # Primary group for oracle_user. 

  oracle_sw_source_www: http://www/orasw     # address to all software if using the get_url module when putting software on the host(s)
  oracle_sw_source_local: /tmp  # Path to all software if using the copy module when putting software on the host(s)
  is_sw_source_local: true
  install_from_nfs: false
  oracle_sw_copy: "{% if install_from_nfs==True %}False{% else %}True{% endif %}"
  oracle_sw_unpack: "{% if install_from_nfs==True %}False{% else %}True{% endif %}"
  nfs_server_sw: nfsserver
  nfs_server_sw_path: /path/to/orasw

  patchpath: "{% if item is defined and item.subpath is defined and item.version is defined %}{{ oracle_stage_install }}/{{ item.version }}/patches/{{ item.subpath }}/{{ item.patchid }}{% endif %}"

  oracle_stage: /u01/stage
  oracle_stage_remote: "{{ oracle_stage }}"
  oracle_stage_install: "{% if oracle_sw_copy==False and oracle_sw_unpack==False%}{{ oracle_stage_remote }}{% else %}{{ oracle_stage }}{% endif %}"
  oracle_base: /u01/app/oracle
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_psu_stage: "{{ oracle_stage }}/psu"

  oracle_hostname: "{{ ansible_fqdn }}"                            # Full (FQDN) name of the host


  oracle_opatch_patch:
       - { filename: p6880880_121010_Linux-x86-64.zip, version: 12.1.0.2 }
       - { filename: p6880880_121010_Linux-x86-64.zip, version: 12.1.0.1 }
       - { filename: p6880880_112000_Linux-x86-64.zip, version: 11.2.0.4 }
       - { filename: p6880880_112000_Linux-x86-64.zip, version: 11.2.0.3 }

